import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import dynamic from "next/dynamic";
import Page from "@components/dom/Page/Page";
import { postFilePaths, POSTS_PATH } from "../utils/mdxUtils";
import Test from "@components/Test";
import React from "react";

// Prefer dynamic import for production builds
// But if you have issues and need to debug in local development
// comment these out and import above instead
// https://github.com/pmndrs/react-three-next/issues/49
const Canvas = dynamic(() => import("@components/3d/Canvas"), {
  ssr: false,
});
const Shader = dynamic(
  () => import("@components/3d/ShaderExample/ShaderExample"),
  {
    ssr: false,
  },
);

export default function Index({ posts }) {
  return (
    <Page>
      <Test />
      {/* <div style={{ width: "400px", height: "400px", margin: "auto" }}>
        <Canvas>
          <Shader />
        </Canvas>
      </div> */}
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`${post.filePath
                .replace(POSTS_PATH, "")
                .replace(/\.mdx?$/, "")}`}
              href={`/posts/[slug]`}
            >
              {post.data.title}
            </Link>
          </li>
        ))}
      </ul>
    </Page>
  );
}

export function getStaticProps() {
  const posts = postFilePaths
    // Remove root path
    .map((filePath) => {
      const source = fs.readFileSync(filePath);
      const { content, data } = matter(source);

      return {
        content,
        data,
        filePath,
      };
    });

  return { props: { posts } };
}
